/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TelemetryRouteImport } from './routes/telemetry'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReplayRouteImport } from './routes/replay'
import { Route as PitwallRouteImport } from './routes/pitwall'
import { Route as NetflixRouteImport } from './routes/netflix'
import { Route as LiveRouteImport } from './routes/live'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TelemetryRoute = TelemetryRouteImport.update({
  id: '/telemetry',
  path: '/telemetry',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReplayRoute = ReplayRouteImport.update({
  id: '/replay',
  path: '/replay',
  getParentRoute: () => rootRouteImport,
} as any)
const PitwallRoute = PitwallRouteImport.update({
  id: '/pitwall',
  path: '/pitwall',
  getParentRoute: () => rootRouteImport,
} as any)
const NetflixRoute = NetflixRouteImport.update({
  id: '/netflix',
  path: '/netflix',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/live': typeof LiveRoute
  '/netflix': typeof NetflixRoute
  '/pitwall': typeof PitwallRoute
  '/replay': typeof ReplayRoute
  '/settings': typeof SettingsRoute
  '/telemetry': typeof TelemetryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/live': typeof LiveRoute
  '/netflix': typeof NetflixRoute
  '/pitwall': typeof PitwallRoute
  '/replay': typeof ReplayRoute
  '/settings': typeof SettingsRoute
  '/telemetry': typeof TelemetryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/live': typeof LiveRoute
  '/netflix': typeof NetflixRoute
  '/pitwall': typeof PitwallRoute
  '/replay': typeof ReplayRoute
  '/settings': typeof SettingsRoute
  '/telemetry': typeof TelemetryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/live'
    | '/netflix'
    | '/pitwall'
    | '/replay'
    | '/settings'
    | '/telemetry'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/live'
    | '/netflix'
    | '/pitwall'
    | '/replay'
    | '/settings'
    | '/telemetry'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/live'
    | '/netflix'
    | '/pitwall'
    | '/replay'
    | '/settings'
    | '/telemetry'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LiveRoute: typeof LiveRoute
  NetflixRoute: typeof NetflixRoute
  PitwallRoute: typeof PitwallRoute
  ReplayRoute: typeof ReplayRoute
  SettingsRoute: typeof SettingsRoute
  TelemetryRoute: typeof TelemetryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/telemetry': {
      id: '/telemetry'
      path: '/telemetry'
      fullPath: '/telemetry'
      preLoaderRoute: typeof TelemetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/replay': {
      id: '/replay'
      path: '/replay'
      fullPath: '/replay'
      preLoaderRoute: typeof ReplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pitwall': {
      id: '/pitwall'
      path: '/pitwall'
      fullPath: '/pitwall'
      preLoaderRoute: typeof PitwallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/netflix': {
      id: '/netflix'
      path: '/netflix'
      fullPath: '/netflix'
      preLoaderRoute: typeof NetflixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LiveRoute: LiveRoute,
  NetflixRoute: NetflixRoute,
  PitwallRoute: PitwallRoute,
  ReplayRoute: ReplayRoute,
  SettingsRoute: SettingsRoute,
  TelemetryRoute: TelemetryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
